apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bookings
  labels:
    name: bookings
spec:
  selector:
    matchLabels:
      name: bookings
  replicas: 2
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        name: bookings
    spec:
      containers:
      - name: bookings
        image: fwblue/bookings:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: bookings
  name: bookings
spec:
  ports:
  selector:
    name: bookings
  type: LoadBalancer
